#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 18 12:58:28 2019

This file contain color schemes to use in all figures

@author: dana_z
"""

def colorPallet(colorType):
    # This function retun a dictionary with pre detrmined colors to be used for
    # all figures during Dana's PhD:
    Colors = {
            'creType':{'MSN':[0.451,0.6,0.667], 'MSN_std':[0.753,0.827,0.863],
                       'CHI':[0.678,0.455,0.686],'CHI_std':[0.867,0.753,0.871],
                       'PV':[1,0.863,0.659], 'PV_std':[1,0.945,0.867]},
            'highLowSpeed':{'high':[0.792,0.925,0.608],'low':[0.678,0.455,0.686]},
            'mvmtType':{'speed':[0,0,0], 'rot':[1,0.573,0], 
                        'phi':[0.02,0.275,0.827], 'acc':[0.004,0.729,0.796]}
            }
    return Colors[colorType]
    
    

 

""" Alternative pallet:
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=b4R3f0l0kaVz84jP27qHbeJtFiHpX


***CHI:

   shade 0 = #A775B0 = rgb(167,117,176) = rgba(167,117,176,1) = rgb0(0.655,0.459,0.69)
   shade 1 = #DAC1DE = rgb(218,193,222) = rgba(218,193,222,1) = rgb0(0.855,0.757,0.871)
   shade 2 = #C29BC9 = rgb(194,155,201) = rgba(194,155,201,1) = rgb0(0.761,0.608,0.788)
   shade 3 = #91569B = rgb(145, 86,155) = rgba(145, 86,155,1) = rgb0(0.569,0.337,0.608)
   shade 4 = #7C3A88 = rgb(124, 58,136) = rgba(124, 58,136,1) = rgb0(0.486,0.227,0.533)

*** MSN (1):

   shade 0 = #6FA8A2 = rgb(111,168,162) = rgba(111,168,162,1) = rgb0(0.435,0.659,0.635)
   shade 1 = #BEDBD8 = rgb(190,219,216) = rgba(190,219,216,1) = rgb0(0.745,0.859,0.847)
   shade 2 = #96C3BE = rgb(150,195,190) = rgba(150,195,190,1) = rgb0(0.588,0.765,0.745)
   shade 3 = #4F938C = rgb( 79,147,140) = rgba( 79,147,140,1) = rgb0(0.31,0.576,0.549)
   shade 4 = #358079 = rgb( 53,128,121) = rgba( 53,128,121,1) = rgb0(0.208,0.502,0.475)

*** PV (2):

   shade 0 = #FFC7A8 = rgb(255,199,168) = rgba(255,199,168,1) = rgb0(1,0.78,0.659)
   shade 1 = #FFE9DD = rgb(255,233,221) = rgba(255,233,221,1) = rgb0(1,0.914,0.867)
   shade 2 = #FFD9C4 = rgb(255,217,196) = rgba(255,217,196,1) = rgb0(1,0.851,0.769)
   shade 3 = #ECA780 = rgb(236,167,128) = rgba(236,167,128,1) = rgb0(0.925,0.655,0.502)
   shade 4 = #CF8256 = rgb(207,130, 86) = rgba(207,130, 86,1) = rgb0(0.812,0.51,0.337)


#####  Generated by Paletton.com (c) 2002-2014
"""
   
    
"""
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=34V1l0kaVz84jP27qHbeJtFiHpX


*** Primary color = CHI:

   shade 0 = #AD74AF = rgb(173,116,175) = rgba(173,116,175,1) = rgb0(0.678,0.455,0.686)
   shade 1 = #DDC0DE = rgb(221,192,222) = rgba(221,192,222,1) = rgb0(0.867,0.753,0.871)
   shade 2 = #C69AC8 = rgb(198,154,200) = rgba(198,154,200,1) = rgb0(0.776,0.604,0.784)
   shade 3 = #98549A = rgb(152, 84,154) = rgba(152, 84,154,1) = rgb0(0.596,0.329,0.604)
   shade 4 = #843887 = rgb(132, 56,135) = rgba(132, 56,135,1) = rgb0(0.518,0.22,0.529)

*** Secondary color (1) = MSN:

   shade 0 = #7399AA = rgb(115,153,170) = rgba(115,153,170,1) = rgb0(0.451,0.6,0.667)
   shade 1 = #C0D3DC = rgb(192,211,220) = rgba(192,211,220,1) = rgb0(0.753,0.827,0.863)
   shade 2 = #99B7C5 = rgb(153,183,197) = rgba(153,183,197,1) = rgb0(0.6,0.718,0.773)
   shade 3 = #548195 = rgb( 84,129,149) = rgba( 84,129,149,1) = rgb0(0.329,0.506,0.584)
   shade 4 = #3A6C82 = rgb( 58,108,130) = rgba( 58,108,130,1) = rgb0(0.227,0.424,0.51)

*** Secondary color (2) = PV:

   shade 0 = #FFDCA8 = rgb(255,220,168) = rgba(255,220,168,1) = rgb0(1,0.863,0.659)
   shade 1 = #FFF1DD = rgb(255,241,221) = rgba(255,241,221,1) = rgb0(1,0.945,0.867)
   shade 2 = #FFE7C4 = rgb(255,231,196) = rgba(255,231,196,1) = rgb0(1,0.906,0.769)
   shade 3 = #ECC180 = rgb(236,193,128) = rgba(236,193,128,1) = rgb0(0.925,0.757,0.502)
   shade 4 = #CF9E56 = rgb(207,158, 86) = rgba(207,158, 86,1) = rgb0(0.812,0.62,0.337)


#####  Generated by Paletton.com (c) 2002-2014
"""
"""
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=a4V2t0kaVz84jP27qHbeJtFiHpX


*** Primary color - low speed:

   shade 0 = #AD74AF = rgb(173,116,175) = rgba(173,116,175,1) = rgb0(0.678,0.455,0.686)
   shade 1 = #DDC0DE = rgb(221,192,222) = rgba(221,192,222,1) = rgb0(0.867,0.753,0.871)
   shade 2 = #C69AC8 = rgb(198,154,200) = rgba(198,154,200,1) = rgb0(0.776,0.604,0.784)
   shade 3 = #98549A = rgb(152, 84,154) = rgba(152, 84,154,1) = rgb0(0.596,0.329,0.604)
   shade 4 = #843887 = rgb(132, 56,135) = rgba(132, 56,135,1) = rgb0(0.518,0.22,0.529)

*** Complement color - high speed:

   shade 0 = #CAEC9B = rgb(202,236,155) = rgba(202,236,155,1) = rgb0(0.792,0.925,0.608)
   shade 1 = #E9F7D6 = rgb(233,247,214) = rgba(233,247,214,1) = rgb0(0.914,0.969,0.839)
   shade 2 = #DAF2BA = rgb(218,242,186) = rgba(218,242,186,1) = rgb0(0.855,0.949,0.729)
   shade 3 = #AFD875 = rgb(175,216,117) = rgba(175,216,117,1) = rgb0(0.686,0.847,0.459)
   shade 4 = #8FBD4F = rgb(143,189, 79) = rgba(143,189, 79,1) = rgb0(0.561,0.741,0.31)


#####  Generated by Paletton.com (c) 2002-2014
"""
"""
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=30I0e0kUhKkqhREBbTqU5tvTrmQ


*** Primary color = Rotation:

   shade 0 = #FF9200 = rgb(255,146,  0) = rgba(255,146,  0,1) = rgb0(1,0.573,0)
   shade 1 = #FFA52E = rgb(255,165, 46) = rgba(255,165, 46,1) = rgb0(1,0.647,0.18)
   shade 2 = #FF9200 = rgb(255,146,  0) = rgba(255,146,  0,1) = rgb0(1,0.573,0)
   shade 3 = #EB8600 = rgb(235,134,  0) = rgba(235,134,  0,1) = rgb0(0.922,0.525,0)
   shade 4 = #B66800 = rgb(182,104,  0) = rgba(182,104,  0,1) = rgb0(0.714,0.408,0)

*** Secondary color (1) = phi:

   shade 0 = #0546D3 = rgb(  5, 70,211) = rgba(  5, 70,211,1) = rgb0(0.02,0.275,0.827)
   shade 1 = #3D73E6 = rgb( 61,115,230) = rgba( 61,115,230,1) = rgb0(0.239,0.451,0.902)
   shade 2 = #1358EB = rgb( 19, 88,235) = rgba( 19, 88,235,1) = rgb0(0.075,0.345,0.922)
   shade 3 = #03359D = rgb(  3, 53,157) = rgba(  3, 53,157,1) = rgb0(0.012,0.208,0.616)
   shade 4 = #03297A = rgb(  3, 41,122) = rgba(  3, 41,122,1) = rgb0(0.012,0.161,0.478)

*** Secondary color (2) ACC:

   shade 0 = #01BACB = rgb(  1,186,203) = rgba(  1,186,203,1) = rgb0(0.004,0.729,0.796)
   shade 1 = #2BD2E2 = rgb( 43,210,226) = rgba( 43,210,226,1) = rgb0(0.169,0.824,0.886)
   shade 2 = #02D4E7 = rgb(  2,212,231) = rgba(  2,212,231,1) = rgb0(0.008,0.831,0.906)
   shade 3 = #00838F = rgb(  0,131,143) = rgba(  0,131,143,1) = rgb0(0,0.514,0.561)
   shade 4 = #00656F = rgb(  0,101,111) = rgba(  0,101,111,1) = rgb0(0,0.396,0.435)


#####  Generated by Paletton.com (c) 2002-2014
"""
